### ISSUE TITLE
Add information for debugging in case that `CanvasCamera` plugin is missing.

### ISSUE THREAD

**Issue by asial-matagawa** [pablomatgar/Japanese-Sign-Language-Interpreter#25]
@pablomatgar 
I just now noticed that the [CanvasCamera](https://www.npmjs.com/package/com.virtuoworks.cordova-plugin-canvascamera) plugin is not a core Cordova plugin and we need to build a custom Monaca Debugger because the store-version Monaca Debugger does not contain the CanvasCamera plugin.

In software development, several types of accidents will happen. To prevent accidents, I recommend doing the following things:

## 1. Add `Testing` section into README.

If you explore GitHub repositories, you may find various section names in their README like:
- Introduction
- Prerequisites
- Requirements
- Setup
- Installation
- Documentation
- Examples
- Contributing
- Changelog
- Testing
- License
- etc.

In this case, I think we can add `Testing` section with a short text:

>## Testing
>You need to build a [custom Monaca Debugger](https://en.docs.monaca.io/products_guide/debugger/installation/debugger_ios#building-a-custom-monaca-debugger) which contains [CanvasCamera](https://www.npmjs.com/package/com.virtuoworks.cordova-plugin-canvascamera) plugin.

## 2. Show error messages for debugging.

In this case, we can show an error message like `window.plugin.CanvasCamera was not found` in the app screen.

----

These changes are optional, but it will help team development in most cases.

I will be glad if you learn such non-technical tips in this opportunity. Thank you!

**Comment by pablomatgar** [comment]
@asial-matagawa Thank you for creating this issue. I also would like to use this opportunity to learn non-technical tips :)
