### ISSUE TITLE
`npm run dev` failed

### ISSUE THREAD

**Issue by yong-asial** [pablomatgar/Japanese-Sign-Language-Interpreter#27]
```
➜  Japanese-Sign-Language-Interpreter git:(main) npm run dev

> jsl@1.0.0 dev
> webpack serve --config ./script/webpack.config.js

[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'disableHostCheck'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
 ```

I think it might due to upgrading the dependencies (webpack and webpack-dev-server).

if you wanna use newer version, you might need to change some webpack configuration. if it is hard to resolve, you can revert back to older version.

In any case, please try to do the full testing

- in local: npm i, npm run build and monaca preview
- in cloud
- build with iOS debug and testing on iphone device
- build with android debug
- testing on android device (optional since you don't have android phone)

**Comment by pablomatgar** [comment]
I tried the full testing and works
