### ISSUE TITLE
The camera is not working properly on iphone and android

### ISSUE THREAD

**Issue by yong-asial** [pablomatgar/Japanese-Sign-Language-Interpreter#28]
Sometimes, 
- the app doesn't show camera
- this dialog `window.plugin.CanvasCamera was not found` is alert

I think it is due to the timing when you call `start()` function.

For example, why there are 2 `start()` function calling?
- https://github.com/pablomatgar/Japanese-Sign-Language-Interpreter/blob/main/src/pages/home.vue#L231
- https://github.com/pablomatgar/Japanese-Sign-Language-Interpreter/blob/main/src/pages/home.vue#L255

Maybe you forgot to remove one of them?

Please check it and test it again on custom debugger for iphone. 

Thank you

**Comment by pablomatgar** [comment]
I forgot to remove one. Now it works good. Thank you.
